# Generated by Django 2.1.1 on 2019-06-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_time',
            field=models.FloatField(null=True),
        ),
    ]
