# Generated by Django 2.1.1 on 2019-05-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
