# Generated by Django 2.1.1 on 2019-05-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_doing',
            field=models.BooleanField(default=False),
        ),
    ]
