# Generated by Django 2.1.1 on 2019-05-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_doing'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assignee_id',
            field=models.IntegerField(default=0),
        ),
    ]
