# Generated by Django 2.1.1 on 2019-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_assignee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='assignee_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
