# Generated by Django 2.1.1 on 2019-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190515_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
    ]
