# Generated by Django 2.1.1 on 2019-05-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_progress_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='actual_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='default_cost',
            field=models.FloatField(null=True),
        ),
    ]
