# Generated by Django 2.1.1 on 2019-05-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=models.IntegerField(null=True),
        ),
    ]
