# Generated by Django 2.1.1 on 2019-05-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190528_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=models.FloatField(null=True),
        ),
    ]
