# Generated by Django 2.1.1 on 2019-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190528_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='done_time',
            field=models.FloatField(null=True),
        ),
    ]
