# Generated by Django 2.1.1 on 2018-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetsTurnover', models.DecimalField(decimal_places=16, max_digits=30)),
                ('CurrentAssetsTurnover', models.DecimalField(decimal_places=16, max_digits=20)),
                ('CurrentRatio', models.DecimalField(decimal_places=16, max_digits=20)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('EBITMargin', models.DecimalField(decimal_places=16, max_digits=20)),
                ('GrossMargin', models.DecimalField(decimal_places=16, max_digits=20)),
                ('Index', models.DecimalField(decimal_places=16, max_digits=20)),
                ('IndustryCode', models.CharField(max_length=120)),
                ('InventoryTurnover', models.DecimalField(decimal_places=16, max_digits=20)),
                ('LTDebtToEquity', models.DecimalField(decimal_places=16, max_digits=20)),
                ('MarketCapitalization', models.CharField(blank=True, max_length=120, null=True)),
                ('Name', models.CharField(max_length=120)),
                ('OperatingMargin', models.DecimalField(decimal_places=16, max_digits=20)),
                ('PB', models.DecimalField(decimal_places=16, max_digits=20)),
                ('PE', models.DecimalField(decimal_places=16, max_digits=20)),
                ('PS', models.DecimalField(decimal_places=16, max_digits=20)),
                ('ProfitMargin', models.DecimalField(decimal_places=16, max_digits=20)),
                ('QuickRatio', models.DecimalField(decimal_places=16, max_digits=20)),
                ('ROA', models.DecimalField(decimal_places=16, max_digits=20)),
                ('ROE', models.DecimalField(decimal_places=16, max_digits=20)),
                ('ROIC', models.DecimalField(decimal_places=16, max_digits=20)),
                ('ReceivablesTurnover', models.DecimalField(decimal_places=16, max_digits=20)),
                ('TotalDebtToEquity', models.DecimalField(decimal_places=16, max_digits=20)),
                ('TotalDebtToTotalAssets', models.DecimalField(decimal_places=16, max_digits=20)),
            ],
        ),
    ]
