# Generated by Django 2.1.1 on 2018-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='InventoryTurnover',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
    ]
