# Generated by Django 2.1.1 on 2018-10-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0002_auto_20181020_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='AssetsTurnover',
            field=models.DecimalField(decimal_places=16, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='CurrentAssetsTurnover',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='CurrentRatio',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='EBITMargin',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='GrossMargin',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='Index',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='LTDebtToEquity',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='OperatingMargin',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='PB',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='PE',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='PS',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ProfitMargin',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='QuickRatio',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ROA',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ROE',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ROIC',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ReceivablesTurnover',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='TotalDebtToEquity',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='TotalDebtToTotalAssets',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
    ]
