# Generated by Django 2.1.1 on 2019-05-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('searchWord', models.CharField(max_length=120, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
