# Generated by Django 2.1.1 on 2019-06-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='time',
        ),
    ]
