# Generated by Django 2.1.1 on 2018-10-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20181030_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publish',
            field=models.DateField(blank=True),
        ),
    ]
