# Generated by Django 2.1.1 on 2018-10-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20181030_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='publish',
        ),
    ]
