# Generated by Django 2.1.1 on 2019-06-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=120)),
                ('price_data', models.TextField(null=True)),
                ('financial_data', models.TextField(null=True)),
                ('Close', models.FloatField(null=True)),
                ('yesterday_Close', models.FloatField(null=True)),
                ('ROE', models.FloatField(null=True)),
                ('EPS', models.FloatField(null=True)),
                ('Volume', models.FloatField(null=True)),
                ('RSI_14', models.FloatField(null=True)),
                ('RSI_14_diff', models.FloatField(null=True)),
                ('MarketCapitalization', models.FloatField(null=True)),
                ('today_capitalization', models.FloatField(null=True)),
                ('percentage_change_in_price', models.FloatField(null=True)),
                ('percentage_change_in_volume', models.FloatField(null=True)),
            ],
        ),
    ]
