# Generated by Django 2.1.1 on 2019-08-04 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price_data',
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated_database',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
