# Generated by Django 2.1.1 on 2019-05-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20190522_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='EPS',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ROE',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='RSI_14',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='RSI_14_diff',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_capitalization',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.TextField(null=True),
        ),
    ]
