# Generated by Django 2.1.1 on 2019-05-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20190523_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='close',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='market_capitalization',
            new_name='MarketCapitalization',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='Symbol',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='volume',
            new_name='Volume',
        ),
    ]
