# Generated by Django 2.1.1 on 2019-05-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_todaycapitalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='percentage_change_in_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='percentage_change_in_volume',
            field=models.FloatField(null=True),
        ),
    ]
