# Generated by Django 2.1.1 on 2019-05-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20190528_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='TodayCapitalization',
            new_name='today_capitalization',
        ),
    ]
