# Generated by Django 2.1.1 on 2019-05-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20190528_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Open',
            field=models.FloatField(null=True),
        ),
    ]
