# Generated by Django 2.1.1 on 2019-05-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_stock_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Open',
            new_name='yesterday_Close',
        ),
    ]
