# Generated by Django 2.1.1 on 2019-07-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinder',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
